spring:
  application:
    name: cubic-proxy
#  security:
#    user:
#      name: admin
#      password: admin
  profiles:
    active: dev

server:
  port: 6080
  tomcat:
    accesslog:
      enabled: true
      directory: ${log.path}/${spring.application.name}
      pattern:  -| %t | %a |  %h | %H | %m | %{x-Forwarded-For}i | %l | %u | %r | %s | %b
matrix:
  server:
    agentPort: 11900
management:
  endpoints:
    web:
      base-path: /

log:
  level: info
  path: /tmp/logs
