spring:
  application:
    name: cubic-proxy
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cubic;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
#    schema: classpath:db/schema.sql
    username: cubic
    password: cubic
  h2:
    console:
      path: /console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 6080
  tomcat:
    accesslog:
      enabled: true
      directory: ${log.path}/${spring.application.name}
      pattern:  -| %t | %a |  %h | %H | %m | %{x-Forwarded-For}i | %l | %u | %r | %s | %b
matrix:
  server:
    agentPort: 11900
management:
  endpoints:
    web:
      base-path: /

log:
  level: info
  path: /tmp/logs
